spring:
  profiles:
    include: secret, aws
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  messages:
    encoding: UTF-8
logging.level:
  org.hibernate.SQL: debug
